"use client";

import { useMemo, useState } from "react";

type View = "home"|"dashboard"|"directory"|"memberships"|"resources"|"admin"|"campaigns";

const members = [
  {name:"Maya Johnson",org:"EFF",chapter:"Howard University",major:"Public Health",year:"2027",role:"Chapter President"},
  {name:"Jordan Ellis",org:"PGWS",chapter:"National Member",major:"Business",year:"2028",role:"Member"},
  {name:"Nia Thompson",org:"EFF + PGWS",chapter:"Delaware State University",major:"Psychology",year:"2026",role:"Mentor"},
  {name:"Avery Brooks",org:"EFF",chapter:"Louisiana State University",major:"Education",year:"2027",role:"Treasurer"},
];

const resources = [
  ["Leadership Training Portal","Courses, certificates, and executive-board preparation","Leadership"],
  ["Chapter Resource Hub","National forms, chapter tools, and officer resources","Chapters"],
  ["Esther’s Light","Faith, prayer, and spiritual-development resources","Faith"],
  ["REACH Action Hub","Student success and stay-enrolled support","Student Success"],
  ["Scholarship Directory","Scholarships and application support","Scholarships"],
  ["EFF Support Hub","Request guidance and find trusted resources","Support"],
];

function Mark({pink=false}:{pink?:boolean}){return <span className={pink?"mark pink":"mark"}>E<span>F</span>F</span>}

export default function Home(){
  const [view,setView]=useState<View>("home");
  const [org,setOrg]=useState<"EFF"|"PGWS">("EFF");
  const [query,setQuery]=useState("");
  const filtered=useMemo(()=>members.filter(m=>`${m.name} ${m.org} ${m.chapter} ${m.major} ${m.role}`.toLowerCase().includes(query.toLowerCase())),[query]);
  const go=(next:View)=>{setView(next);window.scrollTo({top:0,behavior:"smooth"})};
  return <main className={org==="PGWS"?"pgws-theme":""}>
    <header className="topbar"><button className="brand" onClick={()=>go("home")}><Mark pink={org==="PGWS"}/><span><b>EFF CONNECT</b><small>Every Future Fulfilled</small></span></button><nav>{[["dashboard","My Hub"],["directory","Directory"],["memberships","Memberships"],["resources","Resources"],["admin","Command Center"]].map(([id,label])=><button key={id} onClick={()=>go(id as View)} className={view===id?"active":""}>{label}</button>)}</nav><div className="org-switch"><button className={org==="EFF"?"chosen":""} onClick={()=>setOrg("EFF")}>EFF</button><button className={org==="PGWS"?"chosen":""} onClick={()=>setOrg("PGWS")}>PGWS</button></div></header>

    {view==="home"&&<><section className="hero"><div className="hero-copy"><p className="eyebrow">ONE COMMUNITY · TWO ORGANIZATIONS · EVERY FUTURE FULFILLED</p><h1>Your people.<br/><em>Your purpose.</em><br/>Connected.</h1><p>EFF Connect brings membership, chapters, communication, resources, payments, and leadership into one welcoming home for Esther Funds Foundation and Pretty Girls Who Serve.</p><div className="actions"><button className="primary" onClick={()=>go("dashboard")}>Enter EFF Connect →</button><button className="secondary" onClick={()=>go("memberships")}>Explore membership</button></div><div className="trust"><span>Secure member accounts</span><span>Private organization directories</span><span>Built for national growth</span></div></div><div className="hero-card"><div className="member-card"><p>ESTHER FUNDS FOUNDATION</p><Mark/><h3>SHAYNA VINCENT</h3><span>Founder · National Leadership</span><footer><b>EFF CONNECT</b><small>MEMBER SINCE 2024</small></footer></div><div className="float-note"><b>One profile</b><span>EFF + PGWS + every role you hold</span></div></div></section><section className="intro"><p className="script">Belonging should feel beautiful.</p><h2>Everything membership needs,<br/>without the scattered systems.</h2><div className="feature-grid">{[["01","One lasting profile","A member joins once, then adds EFF, PGWS, alumni, mentor, volunteer, or leadership relationships without duplicate accounts."],["02","Two branded homes","EFF and PGWS have separate experiences, colors, membership types, directories, agreements, and permissions."],["03","Real national operations","Payments, mass email, chapters, exports, staff roles, audit history, and Join It migration live in one governed system."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section></>}

    {view==="dashboard"&&<Page title={`Welcome back, Shayna.`} eyebrow={`${org} MEMBER HOME`}><div className="dashboard-grid"><section className="welcome-card"><p className="script">You belong here.</p><h2>Your membership is active.</h2><p>Your profile, organization relationships, receipts, resources, and communication preferences stay connected here.</p><div className="mini-stats"><div><b>2</b><span>memberships</span></div><div><b>1</b><span>leadership role</span></div><div><b>Good</b><span>standing</span></div></div></section><section className="digital-card"><p>DIGITAL MEMBERSHIP CARD</p><h3>SHAYNA VINCENT</h3><span>Founder · EFF & PGWS</span><div><b>EFF-000001</b><small>ACTIVE</small></div></section></div><h2 className="section-title">Your connected spaces</h2><div className="tiles">{[["Memberships","View status, agreements, and receipts","memberships"],["Member directory","Find members by chapter, school, or role","directory"],["Resources","Open training, chapter, faith, and scholarship tools","resources"],["Communication preferences","Control optional email and text updates","dashboard"]].map(x=><button key={x[0]} onClick={()=>go(x[2] as View)}><b>{x[0]}</b><span>{x[1]}</span><i>→</i></button>)}</div></Page>}

    {view==="memberships"&&<Page title="Memberships that grow with you." eyebrow="YOUR ORGANIZATIONS"><div className="membership-grid"><article className="membership eff"><Mark/><p>ESTHER FUNDS FOUNDATION</p><h2>General Membership</h2><span className="status">Active · Good standing</span><ul><li>Free national membership</li><li>Howard University chapter</li><li>Current agreements accepted</li><li>Executive-board commitment: Paid</li></ul><button className="primary">View membership record</button></article><article className="membership pgws"><span className="mirror">✦</span><p>PRETTY GIRLS WHO SERVE</p><h2>Lifetime Membership</h2><span className="status">Active · Paid once</span><ul><li>$20 lifetime membership</li><li>No automatic renewal</li><li>National member directory</li><li>Orientation available</li></ul><button className="dark">View PGWS home</button></article><article className="add-membership"><b>+</b><h3>Add another relationship</h3><p>Join another organization or add an alumni, mentor, volunteer, donor, parent, or partner relationship to this same profile.</p><button className="secondary">Explore eligible options</button></article></div></Page>}

    {view==="directory"&&<Page title="Find your people." eyebrow={`${org} PRIVATE DIRECTORY`}><div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, school, chapter, major, or role"/><button>Filters</button><span>{filtered.length} members</span></div><div className="directory">{filtered.map((m,i)=><article key={m.name}><div className={`avatar a${i}`}>{m.name.split(" ").map(n=>n[0]).join("")}</div><div><p>{m.org}</p><h3>{m.name}</h3><span>{m.role}</span><small>{m.chapter}<br/>{m.major} · Class of {m.year}</small></div><button aria-label={`Open ${m.name}'s profile`}>→</button></article>)}</div><p className="privacy-note">Directory results honor each member’s privacy settings and your organization permissions. Personal documents, payments, and internal records are never displayed.</p></Page>}

    {view==="resources"&&<Page title="Your tools, one click away." eyebrow="MEMBER RESOURCE LIBRARY"><div className="resource-grid">{resources.map((r,i)=><article key={r[0]}><span>0{i+1}</span><small>{r[2]}</small><h3>{r[0]}</h3><p>{r[1]}</p><button>Open resource →</button></article>)}</div><div className="empty-honest"><b>Resource links are managed by authorized staff.</b><span>Production URLs will appear here only after they are reviewed and activated.</span></div></Page>}

    {view==="admin"&&<Page title="The Founder Command Center." eyebrow="NATIONAL OPERATIONS · SHAYNA VINCENT"><div className="admin-stats">{[["20,000","scalable member capacity"],["2","organizations"],["18","active chapters"],["0","data-quality alerts"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><div className="admin-layout"><section><h2>Membership overview</h2><div className="bar-row"><span>EFF active</span><i><b style={{width:"78%"}}/></i><strong>—</strong></div><div className="bar-row pinkbar"><span>PGWS active</span><i><b style={{width:"54%"}}/></i><strong>—</strong></div><p className="data-note">Real totals appear after Supabase is connected. No trend percentages are fabricated.</p></section><section><h2>Operations</h2><div className="admin-links">{["People & memberships","Chapters & regions","Payments & waivers","Administrator access","Reports & exports","Audit log","Join It import","Integration health"].map(x=><button key={x}>{x}<span>→</span></button>)}</div></section></div><div className="command-row"><article><p>COMMUNICATIONS</p><h3>Send the right message to the right members.</h3><button className="primary" onClick={()=>go("campaigns")}>Open Campaign Center</button></article><article><p>ADMINISTRATOR ACCESS</p><h3>Invite staff without sharing your credentials.</h3><button className="secondary">Invite scoped administrator</button></article></div></Page>}

    {view==="campaigns"&&<Page title="Campaign Center." eyebrow="RESEND-POWERED COMMUNICATIONS"><div className="campaign-layout"><section><label>Organization audience<select><option>Esther Funds Foundation</option><option>Pretty Girls Who Serve</option><option>Authorized combined audience</option></select></label><label>Segment<select><option>All active members</option><option>Chapter leaders</option><option>National collegiate members</option><option>Alumni</option><option>Saved segment</option></select></label><label>Subject<input placeholder="A clear, helpful subject line"/></label><label>Message<textarea rows={8} placeholder="Write your message. Use {{first_name}} for personalization."/></label><div className="actions"><button className="secondary">Save draft</button><button className="secondary">Send test</button><button className="primary">Review audience & send</button></div></section><aside><p>FINAL SAFETY CHECK</p><h3>Nothing sends without confirmation.</h3><ul><li>Organization and filters</li><li>Deduplicated recipient count</li><li>Subject and sender</li><li>Suppression and unsubscribe checks</li><li>Test email option</li></ul><span>Resend credentials are required before sending is enabled.</span></aside></div></Page>}

    <footer><div><Mark/><p>EFF Connect is the membership and community home of Esther Funds Foundation and Pretty Girls Who Serve.</p></div><div><b>MEMBER EXPERIENCE</b><button onClick={()=>go("dashboard")}>My Hub</button><button onClick={()=>go("directory")}>Directory</button><button onClick={()=>go("resources")}>Resources</button></div><div><b>ORGANIZATION</b><a href="https://www.estherfundsfoundation.org">Esther Funds Foundation</a><span>Faith-based 501(c)(3)</span><span>EIN 93-4917509</span></div><small>© 2026 Esther Funds Foundation · Every Future Fulfilled.</small></footer>
  </main>
}

function Page({title,eyebrow,children}:{title:string;eyebrow:string;children:React.ReactNode}){return <section className="page"><header><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></header>{children}</section>}
